### ISSUE TITLE
Still an issue with IE8 

### ISSUE THREAD

**Issue by dav3860** [rashidkpc/kibana2#155]
Hi,

I use the latest release of Kibana. It works with Firefox but I have a javascript error with IE8 when opening the start page :
Détails de l’erreur de la page Web

Agent utilisateur : Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
Horodateur : Wed, 14 Nov 2012 10:14:36 UTC

Message : Identificateur, chaîne ou nombre attendu
Ligne : 681
Caractère : 3
Code : 0
URI : http://logsvr1/lib/js/ajax.js

This is the line :
681  }).click(function(e) {
that triggers this error.

/TH

**Comment by rashidkpc** [comment]
Should be fixed, seems to have been caused by an unused polyfill. Tested in IE8 and everything looks ok now.

**Comment by dav3860** [comment]
I'm sorry Rashid, the issue is still here is IE8 :
Détails de l’erreur de la page Web

Agent utilisateur : Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
Horodateur : Mon, 19 Nov 2012 10:03:42 UTC

Message : Identificateur, chaîne ou nombre attendu
Ligne : 679
Caractère : 3
Code : 0
URI : http://logsvr1/lib/js/ajax.js

There seems to be a problem with the "click" event.

**Comment by flyasfish** [comment]
We have exactly the same problem with IE8.

IE version: 8.0.6001.18702CO
kibana version: rashidkpc-Kibana-v0.2.0-0-g41a1298.tar.gz

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727)
Timestamp: Tue, 20 Nov 2012 05:09:11 UTC

Message: Expected identifier, string or number
Line: 679
Char: 3
Code: 0
URI: http://sulog01:5601/lib/js/ajax.js

**Comment by dav3860** [comment]
Hi Rashid, 

I found a few typos in the javascript ajax.js :

> 96c97
> 
> ## <   var sendhash = window.location.hash.replace(/^#/, '');
> 
>   var sendhash = window.location.hash.replace(/^#/, '');;
> 677c678
> 
> ## <     }
> 
> ```
> },
> ```
> 
> 1238c1238
> 
> ## <     grid: {show:false}
> 
> ```
> grid: {show:false},
> ```
> 
> 1355c1355
> 
> ## <         color: "#000"
> 
> ```
>     color: "#000",
> ```

Now, the main page is showing up. But there is still a problem with the datepicker in IE8. No event is fired after I select a date. The picker just disappears when clicked.

**Comment by thomasfr** [comment]
Just drop support for IE < 10 or/and add Google Chrome Frame. It just slows development for a great web app!
