### ISSUE TITLE
Kibana does not respond quickly when bound to network address

### ISSUE THREAD

**Issue by tintii** [rashidkpc/kibana2#95]
Hi,

I've been having issues with kibana when I change the KibanaHost in KibanaConfig.rb from 127.0.0.1 to another address lets say 10.192.254.36 on interface eth1.

The issue is that it's extremely slow to respond... i've gotten to loading the webpage name so far...

when it's hosted on 127.0.0.1 it loads instantly.

any ideas?

thanks

**Comment by rashidkpc** [comment]
Hmm, I havent experienced this. What version of ruby are you on? Do you see the same behavior when running with KibanaHost set to 0.0.0.0?

**Comment by drewp** [comment]
I saw this but I don't have time at the moment to investigate more. 

It looked like the server was doing a dns lookup on client addresses before answering them (!), and that dns timeouts for my internal addresses were making things slow. I stopped caring because my setup plan is to have a local nginx proxying all my /kibana/ requests over to http://127.0.0.1:1234/, so kibana won't see any requests except from localhost.

**Comment by rashidkpc** [comment]
Some digging led me to webrick's :DoNotReverseLookup setting. By default it is set to nil, setting it to true should resolve the issue. I'll look into a way to add this to Kibana

**Comment by tintii** [comment]
Ruby version 1.8.7

still have the issue when running on 0.0.0.0, is there any way to change the webrick setting from outside kibana?

thanks

edit: changed to ruby 1.9.1 - set :DoNotReverseLookup => true, working like a charm so far.

**Comment by rashidkpc** [comment]
Per jordansissel's recommendation I added 'thin' to the gemfile so that webrick wouldn't be used by default. Should fix this

**Comment by drewp** [comment]
Where did this fix get in? I don't think I have it, and I'm on the current rev (https://github.com/rashidkpc/Kibana/commit/81382c65fb9e63407347a12117b39c301f657d7a).

In fact, if I make one request to non-localhost, all subsequent requests, even to localhost, are very slow. strace shows a lot of fast futex and select wait calls that I don't see on a kibana process that hasn't been touched as non-localhost.

**Comment by rashidkpc** [comment]
You're right, it somehow made it out. I readded it to kibana.gemspec. Do a pull and a 'bundle install' and kibana should switch to using thin instead of webrick
